#!/usr/bin/env bash
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
./arm-softmmu/qemu-system-arm \
-M virt \
-append 'root=/dev/vda' \
-cpu cortex-a15 \
-drive file="${dir}/out/arm/buildroot/images/rootfs.ext2.qcow2,if=virtio,format=qcow2" \
-kernel "${dir}/out/arm/buildroot/images/zImage" \
-serial mon:stdio \
"$@" \
;
