#!/usr/bin/env bash
set -eu
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
arch=arm
cmd="\
time \
./${arch}-softmmu/qemu-system-${arch} \
-M virt \
-cpu cortex-a15 \
-append 'root=/dev/vda nokaslr norandmaps printk.devkmsg=on printk.time=y - lkmc_eval=\"/rand_check.out;/sbin/ifup -a;wget -S google.com;/poweroff.out;\"' \
-kernel "${dir}/out/${arch}/buildroot/images/zImage" \
-nographic \
\
-drive file="${dir}/out/${arch}/buildroot/images/rootfs.ext2.qcow2,if=none,format=qcow2,id=img-direct,snapshot" \
-drive driver=blkreplay,if=none,image=img-direct,id=img-blkreplay \
-device virtio-blk-device,drive=img-blkreplay \
\
-device rtl8139,netdev=net1 \
-netdev user,id=net1 \
-object filter-replay,id=replay,netdev=net1 \
"
cmd="${cmd} $@"
echo "$cmd"
eval "$cmd -icount 'shift=7,rr=record,rrfile=replay.bin'"
eval "$cmd -icount 'shift=7,rr=replay,rrfile=replay.bin'"
